# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    acl: "puppetlabs/acl"
    yumrepo_core: "puppetlabs/yumrepo_core"
    augeasproviders_core: "herculesteam/augeasproviders_core"
    augeasproviders_shellvar: "herculesteam/augeasproviders_shellvar"
    augeasproviders_sysctl: "herculesteam/augeasproviders_sysctl"
    windows_env: "puppet/windows_env"
    selinux: "puppet/selinux"
    archive: 'puppet/archive'
