#!/bin/sh

CLUSTER_AUTH=PT_
KEYTAB_PATH=PT_
PEM_PATH=PT_
CA_PATH=PT_
BINDALL=PT_
PORT=PT_
SSLMODE=PT_
ENCRYPTION=PT_
ENCRYPTION_KEYFILE=PT_
REPLICASET_NAME=PT_
OPS_MANAGER_URL=PT_
PROJECT_ID=PT_
LOCAL_CA_PATH=PT_
USERNAME=PT_
PASSWORD=PT_

TMP_FILE="${PROJECT_ID}_${`date --iso-8601=ns`}.json"
cat <<EOF> "/tmp/$(date_"

curl -H 'Content-Type application/json' --digest -u "${USERNAME}:${PASSWORD}" "${OPS_MANAGER_URL}/api/public/v1.0/groups/${PROJECT_ID}/automationConfig"


